name: Publish Text File on Push

on: 
  push:
    branches:
      - main # Adjust this as necessary

jobs:
  prepare_text_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create a random text file
      - name: Create Random Text File
        run: |
          echo "Random Content $(date)" > random_text_file.txt
          cat random_text_file.txt

      # This step simulates a build step you might have
      - name: Simulate Build Step
        run: echo "Building project..."

  wait_for_approval:
    needs: prepare_text_file
    runs-on: ubuntu-latest
    environment: staging-workflow # Ensure this environment is set up for manual approvals
    steps:
      - name: Dummy Approval Step
        run: echo "This step waits for manual approval in the 'staging-workflow' environment."

  # This step would follow after manual approval
  apply_changes:
    needs: wait_for_approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply Changes
        run: |
          echo "Applying changes..."
          # Here you would have steps that use the text file created earlier or other actions.
          # Since GitHub Actions don't share filesystem state between jobs, you'd likely upload/download artifacts or have other mechanisms to share state.
