name: Automated PR Creation and Commenting

on: 
  push:
    branches:
      - main


jobs:
  create_and_comment_pr:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate unique branch name
        run: echo "new-branch-name=$(date +'%Y%m%d%H%M%S')-random" >> $GITHUB_ENV

      - name: Create Random Text File
        run: |
          echo "Random Content $(date)" > random_text_file.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b ${{ env.new-branch-name }}
          git add random_text_file.txt
          git commit -m "Add random text file"
          git push --set-upstream origin ${{ env.new-branch-name }}

      - name: Create Pull Request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.new-branch-name }}
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated PR to merge ${env.new-branch-name} into main"
          pr_body: "This is an automated pull request to update from branch ${{ env.new-branch-name }}"

      - name: Post PR Comment with File Content
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            // Read the content of the random text file
            const content = fs.readFileSync('random_text_file.txt', { encoding: 'utf8' });
            // Post the content as a comment on the PR
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.create_pr.outputs.pr_number }},
              body: `Content of the automatically generated text file:\n\n\`\`\`\n${content}\n\`\`\``,
            });
